apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: supabase
resources:
  - ../base
patches:
  - target:
      kind: Cluster
      name: supabase-pg
    patch: |
      - op: replace
        path: /metadata/namespace
        value: supabase
  - target:
      kind: Database
      name: supabase-db
    patch: |
      - op: replace
        path: /metadata/namespace
        value: supabase
